name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LINODE_SSH_KEY }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519

      - name: Sync to origin/main on Linode
        env:
          HOST:         ${{ secrets.LINODE_HOST }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ssh -i $HOME/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=no \
              deploy@$HOST << 'EOF'
            cd /var/www/julian-api

            # 1) Point origin at HTTPS + token
            git remote set-url origin \
              https://x-access-token:${GITHUB_TOKEN}@github.com/jdiax3004/julian-api.git

            # 2) Download fresh main
            git fetch origin main

            # 3) Throw away any local drift
            git reset --hard origin/main

            # 4) Log exactly what’s now deployed
            echo "✅ Deployed HEAD: $(git rev-parse HEAD)"
            ls -l   # show file timestamps for sanity
          EOF
