name: Deploy to Linode

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ───────────────────────────────────────────────────────────
      # Ensure the Linode host key is trusted
      - name: Add Linode to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.LINODE_HOST }} >> ~/.ssh/known_hosts

      # ───────────────────────────────────────────────────────────
      - name: Pull latest on Linode
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     ${{ secrets.LINODE_HOST }}
          username: deploy
          key:      ${{ secrets.LINODE_SSH_KEY }}
          script: |
            cd /var/www/julian-api
            git pull origin main
            # ─ Optional: build or restart
            # npm ci && npm run build
            # pm2 reload all || sudo systemctl restart your-service
