name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1) Install the runner→Linode SSH key
      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LINODE_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      # 2) SSH in and reset the repo to match origin/main
      - name: Hard‐reset repo on Linode
        env:
          HOST: ${{ secrets.LINODE_HOST }}
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=no \
              deploy@$HOST << 'EOF'
            cd /var/www/julian-api
            git fetch origin main
            git reset --hard origin/main
            # ─ Optional build/restart steps ─
            # npm ci && npm run build
            # pm2 reload all || sudo systemctl restart your-service
          EOF
