name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Install your SSH private key
      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LINODE_SSH_KEY }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519

      # 3) SSH in and pull latest
      - name: Pull on Linode
        env:
          HOST: ${{ secrets.LINODE_HOST }}
        run: |
          ssh -i $HOME/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              deploy@$HOST \
              "cd /var/www/julian-api && git pull origin main"
