name: Deploy to Linode

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up SSH key + known_hosts
      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LINODE_SSH_KEY }}
          HOST:            ${{ secrets.LINODE_HOST }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # write your private key
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # scan & trust your Linode’s host key
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

- name: Pull on Linode
  env:
    HOST: ${{ secrets.LINODE_HOST }}
  run: |
    ssh -i ~/.ssh/id_ed25519 \
        -o StrictHostKeyChecking=no \
        deploy@"$HOST" \
        "cd /var/www/julian-api && git pull origin main"

